### ISSUE TITLE
Crash when installing app through root if no root access

### ISSUE THREAD

**Issue by osjasmine** [Iamlooker/Droid-ify#109]
I dont know if its something with my phone or the root app but if droidify has root access denied but install method is chosen as root, it crashes when it is trying to install an app (after downloading it).

Here is some error from logcat related to the above situation:
```kotlin
FATAL EXCEPTION: main
Process: com.looker.droidify, PID: 15725
java.lang.NoClassDefFoundError: <clinit> failed for class com.looker.installer.installer.RootInstaller; see exception in other thread
	at com.looker.installer.AppInstaller$Companion$getInstance$1$1$1.getDefaultInstaller(AppInstaller.kt:2)
	at com.looker.droidify.utility.extension.app_file.InstallExtensionKt$installApk$2.invokeSuspend(InstallExtension.kt:27)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@72b53a9, Dispatchers.Main.immediate]

```
 Also happens when shizuku is the install method (with shizuku in root mode).

Android: 10
Phone: samsung a10
Non-magisk root (some generic superuser)

**Comment by Bugaddr** [comment]
Why not use magisk ?

**Comment by osjasmine** [comment]
Yeah thats true but right now it will be too much of hassle to change to magisk. Back then I didnt have good knowledge of root and stuff so I just went with the simplest method, a one-root app.

**Comment by Iamlooker** [comment]
This should be fixed next release, ping me to reopen this issue if it is not fixed
