### ISSUE TITLE
Crashes when author card clicked 

### ISSUE THREAD

**Issue by damionx7** [Iamlooker/Droid-ify#114]
Here is the attached log

```
FATAL EXCEPTION: main
Process: com.looker.droidify, PID: 28331
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat= }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2079)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1739)
	at android.app.Activity.startActivityForResult(Activity.java:5314)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
	at android.app.Activity.startActivityForResult(Activity.java:5272)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:583)
	at android.app.Activity.startActivity(Activity.java:5658)
	at android.app.Activity.startActivity(Activity.java:5611)
	at com.looker.droidify.screen.ProductAdapter.onBindViewHolder$lambda-58(ProductAdapter.kt:1264)
	at com.looker.droidify.screen.ProductAdapter.$r8$lambda$EiSc_2QAoRH4cbeXRzg2UQQRiis(Unknown Source:0)
	at com.looker.droidify.screen.ProductAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7448)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28306)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

I am using my custom fdroid repository `https://thedoc.eu.org/fdroid/repo` and when I click on author, I get this crash.

**Comment by mondlicht-und-sterne** [comment]
I don't get an error. So it's not a general problem (that's just for my information).

**Comment by damionx7** [comment]
https://github.com/Iamlooker/Droid-ify/blob/248ec7808033a67f33eadada15233ccd44472863/src/main/kotlin/com/looker/droidify/screen/ProductAdapter.kt#L1278-L1280

Can you put checks here so that the app doesn't crash ?

**Comment by Iamlooker** [comment]
> 
> 
> https://github.com/Iamlooker/Droid-ify/blob/248ec7808033a67f33eadada15233ccd44472863/src/main/kotlin/com/looker/droidify/screen/ProductAdapter.kt#L1278-L1280
> 
> Can you put checks here so that the app doesn't crash ?

Already did this just gotta push
