### ISSUE TITLE
Crash when root permission is allowed

### ISSUE THREAD

**Issue by ygz213** [Iamlooker/Droid-ify#120]
**OS:** Android 5.0.1
**Root type:** Magisk

This crash does not occur when I deny root permission in Magisk (even silent installation is active)

**Logcat** (`adb logcat | findstr com.looker.droidify`)
```
D/ActivityThread(12905): SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@1bb35431 className=com.looker.droidify.service.SyncService$Job packageName=com.looker.droidify intent=null}
D/ActivityThread(12905): SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@1bb35431 className=com.looker.droidify.service.SyncService$Job packageName=com.looker.droidify intent=null}
D/PowerManagerService(  552): acquireWakeLockInternal: lock=471295546, flags=0x1, tag="*job*/com.looker.droidify/.service.SyncService$Job", ws=WorkSource{10330}, uid=1000, pid=552
D/ActivityThread(12905): SVC-BIND_SERVICE handled : 0 / BindServiceData{token=android.os.BinderProxy@1bb35431 intent=Intent { cmp=com.looker.droidify/.service.SyncService$Job }}
D/PowerManagerNotifier(  552): onWakeLockAcquired: flags=1, tag="*job*/com.looker.droidify/.service.SyncService$Job", packageName=android, ownerUid=1000, ownerPid=552, workSource=WorkSource{10330}
D/ActivityThread(12905): SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@2b38026d className=com.looker.droidify.service.SyncService packageName=com.looker.droidify intent=null}
D/ActivityThread(12905): SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@2b38026d className=com.looker.droidify.service.SyncService packageName=com.looker.droidify intent=null}
D/ActivityThread(12905): SVC-BIND_SERVICE handled : 0 / BindServiceData{token=android.os.BinderProxy@2b38026d intent=Intent { cmp=com.looker.droidify/.service.SyncService }}
D/ActivityThread(12905): SVC-UNBIND_SERVICE handled : 0 / BindServiceData{token=android.os.BinderProxy@2b38026d intent=Intent { cmp=com.looker.droidify/.service.SyncService }}
D/ActivityThread(12905): SVC-Destroying service: com.looker.droidify.service.SyncService@31fbd39e
D/PowerManagerService(  552): releaseWakeLockInternal: lock=471295546 [*job*/com.looker.droidify/.service.SyncService$Job], flags=0x0, total_time=2390ms
D/PowerManagerNotifier(  552): onWakeLockReleased: flags=1, tag="*job*/com.looker.droidify/.service.SyncService$Job", packageName=android, ownerUid=1000, ownerPid=552, workSource=WorkSource{10330}
D/ActivityThread(12905): SVC-UNBIND_SERVICE handled : 0 / BindServiceData{token=android.os.BinderProxy@1bb35431 intent=Intent { cmp=com.looker.droidify/.service.SyncService$Job }}
D/ActivityThread(12905): SVC-Destroying service: com.looker.droidify.service.SyncService$Job@3a111897
D/ActivityThread(12905): SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@ce76e7f className=com.looker.droidify.service.SyncService$Job packageName=com.looker.droidify intent=null}
D/ActivityThread(12905): SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@ce76e7f className=com.looker.droidify.service.SyncService$Job packageName=com.looker.droidify intent=null}
D/ActivityThread(12905): SVC-BIND_SERVICE handled : 0 / BindServiceData{token=android.os.BinderProxy@ce76e7f intent=Intent { cmp=com.looker.droidify/.service.SyncService$Job }}
D/PowerManagerService(  552): acquireWakeLockInternal: lock=876642962, flags=0x1, tag="*job*/com.looker.droidify/.service.SyncService$Job", ws=WorkSource{10330}, uid=1000, pid=552
D/PowerManagerNotifier(  552): onWakeLockAcquired: flags=1, tag="*job*/com.looker.droidify/.service.SyncService$Job", packageName=android, ownerUid=1000, ownerPid=552, workSource=WorkSource{10330}
D/ActivityThread(12905): SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@2a8e739b className=com.looker.droidify.service.SyncService packageName=com.looker.droidify intent=null}
D/ActivityThread(12905): SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@2a8e739b className=com.looker.droidify.service.SyncService packageName=com.looker.droidify intent=null}
D/ActivityThread(12905): SVC-BIND_SERVICE handled : 0 / BindServiceData{token=android.os.BinderProxy@2a8e739b intent=Intent { cmp=com.looker.droidify/.service.SyncService }}
I/ActivityManager(  552): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.looker.droidify/.MainActivity} from uid 10324 on display 0
D/ActivityManager(  552): [BMW] insertTaskAtTop fromHome = true lastStack = ActivityStack{2895941d stackId=0, 3 tasks} this = ActivityStack{346f3d4e stackId=1, 2 tasks} topTask() = TaskRecord{1c7f45d5 #201 A=com.looker.droidify U=0 sz=0}
V/ActivityThread(12905): Handling launch of ActivityRecord{2a2b3b4d token=android.os.BinderProxy@b07e602 {com.looker.droidify/com.looker.droidify.MainActivity}}
W/ActivityManager(  552):   Force finishing activity com.looker.droidify/.MainActivity
I/WindowManager(  552): Screenshot max retries 4 of Token{1d49f378 ActivityRecord{cb5ba8c u0 com.looker.droidify/.MainActivity t201 f}} appWin=Window{1df3d28e u0 Starting com.looker.droidify} drawState=4
V/WindowManager(  552): Changing focus from null to Window{253543fb u0 Application Error: com.looker.droidify} Callers=com.android.server.wm.WindowManagerService.addWindow:2892 com.android.server.wm.Session.addToDisplay:173 android.view.ViewRootImpl.setView:636 android.view.WindowManagerGlobal.addView:279 
I/WindowManager(  552): Gaining focus: Window{253543fb u0 Application Error: com.looker.droidify}
W/ActivityManager(  552): Activity pause timeout for ActivityRecord{cb5ba8c u0 com.looker.droidify/.MainActivity t201 f}
W/ActivityManager(  552): Activity destroy timeout for ActivityRecord{cb5ba8c u0 com.looker.droidify/.MainActivity t201 f}
V/WindowManager(  552): Changing focus from Window{253543fb u0 Application Error: com.looker.droidify EXITING} to Window{3a6329e1 u0 com.teslacoilsw.launcher/com.teslacoilsw.launcher.NovaLauncher} Callers=com.android.server.wm.WindowManagerService.removeWindowLocked:3025 com.android.server.wm.WindowManagerService.removeWindow:2962 com.android.server.wm.Session.remove:192 android.view.ViewRootImpl.dispatchDetachedFromWindow:3314 
I/WindowManager(  552): Losing focus: Window{253543fb u0 Application Error: com.looker.droidify EXITING}
D/PowerManagerService(  552): releaseWakeLockInternal: lock=876642962 [*job*/com.looker.droidify/.service.SyncService$Job], flags=0x0, total_time=18974ms
D/PowerManagerNotifier(  552): onWakeLockReleased: flags=1, tag="*job*/com.looker.droidify/.service.SyncService$Job", packageName=android, ownerUid=1000, ownerPid=552, workSource=WorkSource{10330}
I/ActivityManager(  552): Process com.looker.droidify (pid 12905) has died
W/ActivityManager(  552): Scheduling restart of crashed service com.looker.droidify/.service.SyncService$Job in 1000ms
I/ActivityManager(  552): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.looker.droidify/.MainActivity} from uid 10324 on display 0
D/ActivityManager(  552): [BMW] insertTaskAtTop fromHome = true lastStack = ActivityStack{2895941d stackId=0, 3 tasks} this = ActivityStack{346f3d4e stackId=1, 2 tasks} topTask() = TaskRecord{34eb7008 #202 A=com.looker.droidify U=0 sz=0}
I/BufferQueueConsumer(  155): [Starting com.looker.droidify](this:0xb2f84000,id:3909,api:0,p:-1,c:155) setConsumerName: Starting com.looker.droidify
I/BufferQueueConsumer(  155): [Starting com.looker.droidify](this:0xb2f84000,id:3909,api:0,p:-1,c:155) setDefaultBufferSize: width=1 height=1
I/BufferQueueConsumer(  155): [Starting com.looker.droidify](this:0xb2f84000,id:3909,api:0,p:-1,c:155) setDefaultBufferSize: width=1280 height=800
I/ActivityManager(  552): Start proc com.looker.droidify for activity com.looker.droidify/.MainActivity: pid=13547 uid=10330 gids={50330, 9997, 3003} abi=armeabi-v7a
I/BufferQueueProducer(  155): [Starting com.looker.droidify](this:0xb2f84000,id:3909,api:2,p:552,c:155) connect(P): api=2 producer=(552:system_server) producerControlledByApp=false
I/BufferQueueProducer(  155): [Starting com.looker.droidify](this:0xb2f84000,id:3909,api:2,p:552,c:155) new GraphicBuffer needed
D/ActivityThread(13547): installProvider: context.getPackageName()=com.looker.droidify
D/ActivityThread(13547): installProvider: context.getPackageName()=com.looker.droidify
D/ActivityThread(13547): BIND_APPLICATION handled : 0 / AppBindData{appInfo=ApplicationInfo{21d5a048 com.looker.droidify}}
V/ActivityThread(13547): Handling launch of ActivityRecord{3e7b5ee1 token=android.os.BinderProxy@34762406 {com.looker.droidify/com.looker.droidify.MainActivity}}
E/AndroidRuntime(13547): Process: com.looker.droidify, PID: 13547
E/AndroidRuntime(13547): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.looker.droidify/com.looker.droidify.MainActivity}: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
E/AndroidRuntime(13547): 	at com.looker.droidify.installer.RootInstaller.<init>(RootInstaller.kt:59)
E/AndroidRuntime(13547): 	at com.looker.droidify.installer.AppInstaller$Companion$getInstance$1$1$1.getDefaultInstaller(AppInstaller.kt:21)
E/AndroidRuntime(13547): 	at com.looker.droidify.screen.ScreenActivity.<init>(ScreenActivity.kt:72)
E/AndroidRuntime(13547): 	at com.looker.droidify.MainActivity.<init>(MainActivity.kt:8)
W/ActivityManager(  552):   Force finishing activity com.looker.droidify/.MainActivity
D/AES     (  552):     process : com.looker.droidify
D/AES     (  552):      module : com.looker.droidify v41 (0.4.1)
D/AEE/LIBAEE(  552): shell: raise_exp(4, 13547, -1361051648, com.looker.droidify, 0x0xa08c4000, 0x0x0)
I/AEE/AED (13585): [OnPurpose Redunant in void preset_info(aed_report_record*, int, int)] pid: 13547, tid: -1361051648, name: UNKNOWN  >>> com.looker.droidify <<<
V/AEE/AED (13585): dashboard_record_update() : rec->module = com.looker.droidify 
D/AEE/AED (13585): Module: com.looker.droidify 
I/WindowManager(  552): Screenshot max retries 4 of Token{2ba83d87 ActivityRecord{22fa31ab u0 com.looker.droidify/.MainActivity t202 f}} appWin=Window{83ef695 u0 Starting com.looker.droidify} drawState=4
V/WindowManager(  552): Changing focus from null to Window{1d39f5ca u0 Application Error: com.looker.droidify} Callers=com.android.server.wm.WindowManagerService.addWindow:2892 com.android.server.wm.Session.addToDisplay:173 android.view.ViewRootImpl.setView:636 android.view.WindowManagerGlobal.addView:279 
I/WindowManager(  552): Gaining focus: Window{1d39f5ca u0 Application Error: com.looker.droidify}
I/BufferQueueConsumer(  155): [Application Error: com.looker.droidify](this:0xb2f95400,id:3910,api:0,p:-1,c:155) setConsumerName: Application Error: com.looker.droidify
I/BufferQueueConsumer(  155): [Application Error: com.looker.droidify](this:0xb2f95400,id:3910,api:0,p:-1,c:155) setDefaultBufferSize: width=87 height=87
I/BufferQueueConsumer(  155): [Application Error: com.looker.droidify](this:0xb2f95400,id:3910,api:0,p:-1,c:155) setDefaultBufferSize: width=790 height=278
I/BufferQueueProducer(  155): [Application Error: com.looker.droidify](this:0xb2f95400,id:3910,api:1,p:552,c:155) connect(P): api=1 producer=(552:system_server) producerControlledByApp=false
I/BufferQueueProducer(  155): [Application Error: com.looker.droidify](this:0xb2f95400,id:3910,api:1,p:552,c:155) new GraphicBuffer needed
D/BufferQueueProducer(  155): [Application Error: com.looker.droidify](this:0xb2f95400,id:3910,api:1,p:552,c:155) cancelBuffer: slot 0
I/BufferQueueProducer(  155): [Application Error: com.looker.droidify](this:0xb2f95400,id:3910,api:1,p:552,c:155) setBufferCount: count = 4
I/BufferQueueConsumer(  155): [Application Error: com.looker.droidify](this:0xb2f95400,id:3910,api:1,p:552,c:155) getReleasedBuffers: returning mask 0xffffffffffffffff
I/BufferQueueProducer(  155): [Application Error: com.looker.droidify](this:0xb2f95400,id:3910,api:1,p:552,c:155) new GraphicBuffer needed
W/ActivityManager(  552): Activity pause timeout for ActivityRecord{22fa31ab u0 com.looker.droidify/.MainActivity t202 f}
I/BufferQueueProducer(  155): [Starting com.looker.droidify](this:0xb2f84000,id:3909,api:2,p:-1,c:155) disconnect(P): api 2
I/BufferQueueConsumer(  155): [Starting com.looker.droidify](this:0xb2f84000,id:3909,api:2,p:-1,c:155) getReleasedBuffers: returning mask 0xffffffffffffffff
I/BufferQueueConsumer(  155): [Starting com.looker.droidify](this:0xb2f84000,id:3909,api:2,p:-1,c:-1) disconnect(C)
I/BufferQueue(  155): [Starting com.looker.droidify](this:0xb2f84000,id:3909,api:2,p:-1,c:-1) ~BufferQueueCore
I/BufferQueueProducer(  155): [Application Error: com.looker.droidify](this:0xb2f95400,id:3910,api:1,p:552,c:155) queueBuffer: fps=5.00 dur=1000.95 max=928.76 min=13.57
W/ActivityManager(  552): Activity destroy timeout for ActivityRecord{22fa31ab u0 com.looker.droidify/.MainActivity t202 f}
E/JobServiceContext(  552): Time-out while trying to bind com.looker.droidify/.service.SyncService$Job jId=1, u0, dropping.
E/JobServiceContext(  552): Time-out while trying to bind com.looker.droidify/.service.SyncService$Job jId=1, u0, dropping.
I/BufferQueueProducer(  155): [Application Error: com.looker.droidify](this:0xb2f95400,id:3910,api:1,p:552,c:155) queueBuffer: fps=0.80 dur=23681.47 max=23271.34 min=11.88
I/BufferQueueProducer(  155): [Application Error: com.looker.droidify](this:0xb2f95400,id:3910,api:1,p:-1,c:155) disconnect(P): api 1
I/BufferQueueConsumer(  155): [Application Error: com.looker.droidify](this:0xb2f95400,id:3910,api:1,p:-1,c:155) getReleasedBuffers: returning mask 0xfffffffffffffffb
V/WindowManager(  552): Changing focus from Window{1d39f5ca u0 Application Error: com.looker.droidify EXITING} to Window{3a6329e1 u0 com.teslacoilsw.launcher/com.teslacoilsw.launcher.NovaLauncher} Callers=com.android.server.wm.WindowManagerService.removeWindowLocked:3025 com.android.server.wm.WindowManagerService.removeWindow:2962 com.android.server.wm.Session.remove:192 android.view.ViewRootImpl.dispatchDetachedFromWindow:3314 
I/WindowManager(  552): Losing focus: Window{1d39f5ca u0 Application Error: com.looker.droidify EXITING}
I/ActivityManager(  552): Process com.looker.droidify (pid 13547) has died
W/ActivityManager(  552): Scheduling restart of crashed service com.looker.droidify/.service.SyncService$Job in 1000ms
I/BufferQueueConsumer(  155): [Application Error: com.looker.droidify](this:0xb2f95400,id:3910,api:1,p:-1,c:-1) disconnect(C)
I/BufferQueue(  155): [Application Error: com.looker.droidify](this:0xb2f95400,id:3910,api:1,p:-1,c:-1) ~BufferQueueCore
I/ActivityManager(  552): Start proc com.looker.droidify for service com.looker.droidify/.service.SyncService$Job: pid=13609 uid=10330 gids={50330, 9997, 3003} abi=armeabi-v7a
D/ActivityThread(13609): installProvider: context.getPackageName()=com.looker.droidify
D/ActivityThread(13609): installProvider: context.getPackageName()=com.looker.droidify
D/ActivityThread(13609): BIND_APPLICATION handled : 0 / AppBindData{appInfo=ApplicationInfo{21d5a048 com.looker.droidify}}
D/ActivityThread(13609): SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@3e7b5ee1 className=com.looker.droidify.service.SyncService$Job packageName=com.looker.droidify intent=null}
D/ActivityThread(13609): SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@3e7b5ee1 className=com.looker.droidify.service.SyncService$Job packageName=com.looker.droidify intent=null}
D/ActivityThread(13609): SVC-BIND_SERVICE handled : 0 / BindServiceData{token=android.os.BinderProxy@3e7b5ee1 intent=Intent { cmp=com.looker.droidify/.service.SyncService$Job }}
D/PowerManagerService(  552): acquireWakeLockInternal: lock=570444215, flags=0x1, tag="*job*/com.looker.droidify/.service.SyncService$Job", ws=WorkSource{10330}, uid=1000, pid=552
D/PowerManagerNotifier(  552): onWakeLockAcquired: flags=1, tag="*job*/com.looker.droidify/.service.SyncService$Job", packageName=android, ownerUid=1000, ownerPid=552, workSource=WorkSource{10330}
D/ActivityThread(13609): SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@166e3060 className=com.looker.droidify.service.SyncService packageName=com.looker.droidify intent=null}
D/ActivityThread(13609): SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@166e3060 className=com.looker.droidify.service.SyncService packageName=com.looker.
```

**Comment by Iamlooker** [comment]
You have to allow in both and restart the app

**Comment by Iamlooker** [comment]
I cant reproduce this

**Comment by Iamlooker** [comment]
Also tell you Android Version

**Comment by ygz213** [comment]
> Also tell you Android Version

Android 5.0.1

> You have to allow in both and restart the app

The crash occurred while silent installation is active and root permission is given. I tried restart but nothing changed.

> What was the last version on which it was working?

I tried on 0.4.1, 0.4.0 and 0.3.6:

- 0.4.0 and 0.4.1 checks root permission at startup and crashes.
- 0.3.6 checks root permission when installing downloaded APK and crashes.

**Comment by Iamlooker** [comment]
Seems like this has been fixed but you have to wait for next release
