### ISSUE TITLE
Crash when installing microG Services Core

### ISSUE THREAD

**Issue by haarp** [Iamlooker/Droid-ify#131]
With the microG F-Droid repo enabled, I am attempting to install the microG Services Core (com.google.android.gms) 0.2.22.212658 via this app. The app finishes the download and then crashes.

From Logcat:

```
11-27 15:43:46.519 21353 21353 E looker.droidif: Invalid ID 0x00000000.
11-27 15:43:46.519 21353 21353 W System.err: io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | android.content.res.Resources$NotFoundException: Resource ID #0x0
11-27 15:43:46.519 21353 21353 W System.err: 	at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:372)
11-27 15:43:46.519 21353 21353 W System.err: 	at io.reactivex.rxjava3.internal.observers.BiConsumerSingleObserver.onSuccess(BiConsumerSingleObserver.java:59)
11-27 15:43:46.519 21353 21353 W System.err: 	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
11-27 15:43:46.519 21353 21353 W System.err: 	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
11-27 15:43:46.519 21353 21353 W System.err: 	at android.os.Handler.handleCallback(Handler.java:883)
11-27 15:43:46.519 21353 21353 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:100)
11-27 15:43:46.519 21353 21353 W System.err: 	at android.os.Looper.loop(Looper.java:214)
11-27 15:43:46.519 21353 21353 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
11-27 15:43:46.519 21353 21353 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
11-27 15:43:46.519 21353 21353 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
11-27 15:43:46.519 21353 21353 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
11-27 15:43:46.519 21353 21353 W System.err: Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
11-27 15:43:46.519 21353 21353 W System.err: 	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:237)
11-27 15:43:46.519 21353 21353 W System.err: 	at android.content.res.Resources.getValue(Resources.java:1351)
11-27 15:43:46.519 21353 21353 W System.err: 	at androidx.core.content.res.ResourcesCompat.isColorInt(ResourcesCompat.java:273)
11-27 15:43:46.519 21353 21353 W System.err: 	at androidx.core.content.res.ResourcesCompat.inflateColorStateList(ResourcesCompat.java:223)
11-27 15:43:46.519 21353 21353 W System.err: 	at androidx.core.content.res.ResourcesCompat.getColorStateList(ResourcesCompat.java:203)
11-27 15:43:46.519 21353 21353 W System.err: 	at androidx.core.content.ContextCompat.getColorStateList(ContextCompat.java:519)
11-27 15:43:46.519 21353 21353 W System.err: 	at com.looker.droidify.utility.extension.resources.ResourcesKt.getColorFromAttr(Resources.kt:74)
11-27 15:43:46.519 21353 21353 W System.err: 	at com.looker.droidify.service.DownloadService.showNotificationError(DownloadService.kt:219)
11-27 15:43:46.519 21353 21353 W System.err: 	at com.looker.droidify.service.DownloadService.handleDownload$lambda-9(DownloadService.kt:468)
11-27 15:43:46.519 21353 21353 W System.err: 	at com.looker.droidify.service.DownloadService.$r8$lambda$PQqjbQoBmgHFfarV8D51DX3TTYg(Unknown Source:0)
11-27 15:43:46.519 21353 21353 W System.err: 	at com.looker.droidify.service.DownloadService$$ExternalSyntheticLambda0.accept(Unknown Source:10)
11-27 15:43:46.519 21353 21353 W System.err: 	at io.reactivex.rxjava3.internal.observers.BiConsumerSingleObserver.onSuccess(BiConsumerSingleObserver.java:56)
11-27 15:43:46.519 21353 21353 W System.err: 	... 9 more
11-27 15:43:46.520 21353 21353 E AndroidRuntime: FATAL EXCEPTION: main
11-27 15:43:46.520 21353 21353 E AndroidRuntime: Process: com.looker.droidify, PID: 21353
11-27 15:43:46.520 21353 21353 E AndroidRuntime: io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | android.content.res.Resources$NotFoundException: Resource ID #0x0
11-27 15:43:46.520 21353 21353 E AndroidRuntime: 	at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:372)
11-27 15:43:46.520 21353 21353 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.observers.BiConsumerSingleObserver.onSuccess(BiConsumerSingleObserver.java:59)
11-27 15:43:46.520 21353 21353 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
11-27 15:43:46.520 21353 21353 E AndroidRuntime: 	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
11-27 15:43:46.520 21353 21353 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
11-27 15:43:46.520 21353 21353 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
11-27 15:43:46.520 21353 21353 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
11-27 15:43:46.520 21353 21353 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
11-27 15:43:46.520 21353 21353 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-27 15:43:46.520 21353 21353 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
11-27 15:43:46.520 21353 21353 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
11-27 15:43:46.520 21353 21353 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
11-27 15:43:46.520 21353 21353 E AndroidRuntime: 	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:237)
11-27 15:43:46.520 21353 21353 E AndroidRuntime: 	at android.content.res.Resources.getValue(Resources.java:1351)
11-27 15:43:46.520 21353 21353 E AndroidRuntime: 	at androidx.core.content.res.ResourcesCompat.isColorInt(ResourcesCompat.java:273)
11-27 15:43:46.520 21353 21353 E AndroidRuntime: 	at androidx.core.content.res.ResourcesCompat.inflateColorStateList(ResourcesCompat.java:223)
11-27 15:43:46.520 21353 21353 E AndroidRuntime: 	at androidx.core.content.res.ResourcesCompat.getColorStateList(ResourcesCompat.java:203)
11-27 15:43:46.520 21353 21353 E AndroidRuntime: 	at androidx.core.content.ContextCompat.getColorStateList(ContextCompat.java:519)
11-27 15:43:46.520 21353 21353 E AndroidRuntime: 	at com.looker.droidify.utility.extension.resources.ResourcesKt.getColorFromAttr(Resources.kt:74)
11-27 15:43:46.520 21353 21353 E AndroidRuntime: 	at com.looker.droidify.service.DownloadService.showNotificationError(DownloadService.kt:219)
11-27 15:43:46.520 21353 21353 E AndroidRuntime: 	at com.looker.droidify.service.DownloadService.handleDownload$lambda-9(DownloadService.kt:468)
11-27 15:43:46.520 21353 21353 E AndroidRuntime: 	at com.looker.droidify.service.DownloadService.$r8$lambda$PQqjbQoBmgHFfarV8D51DX3TTYg(Unknown Source:0)
11-27 15:43:46.520 21353 21353 E AndroidRuntime: 	at com.looker.droidify.service.DownloadService$$ExternalSyntheticLambda0.accept(Unknown Source:10)
11-27 15:43:46.520 21353 21353 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.observers.BiConsumerSingleObserver.onSuccess(BiConsumerSingleObserver.java:56)
11-27 15:43:46.520 21353 21353 E AndroidRuntime: 	... 9 more
11-27 15:43:46.522  1269 22100 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
11-27 15:43:46.523  1269  4251 W ActivityTaskManager:   Force finishing activity com.looker.droidify/.MainActivity
11-27 15:43:46.545 21353 21353 I Process : Sending signal. PID: 21353 SIG: 9
11-27 15:43:46.673  1269  1486 W InputDispatcher: channel '5cc7102 com.looker.droidify/com.looker.droidify.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
11-27 15:43:46.673  1269  1486 E InputDispatcher: channel '5cc7102 com.looker.droidify/com.looker.droidify.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
11-27 15:43:46.675  1269  2788 I ActivityManager: Process com.looker.droidify (pid 21353) has died: fore TOP
```

**Comment by machiav3lli** [comment]
What version and are you using root installer or normal mode?

**Comment by haarp** [comment]
Version 0.4.1 form the official F-Droid repo, normal install mode.

Other apps fro mthe microG repo are also affected, such as FakeStore. Interestingly, I can download and install these apps manually just fine from [here](https://microg.org/download.html), which uses the same URLs and same files as the repository. But then Droidify then thinks the installed version is signed with a different certificate than the one *from the same repo*. Weird.

**Comment by haarp** [comment]
Droidify 0.4.3, still running into issues ith the microG repository. I had `com.google.android.gms-0.2.22` installed from [here](https://microg.org/download.html), which provides the **same apks with the same signature** as the ones offered by the Fdroid repo. Yet Droidify will claim it to be a different signature and not allow upgrades. I could upgrade by manually installing 0.2.24 just fine tho.

**Comment by machiav3lli** [comment]
Is this still on 1.0.0, if not please close
