### ISSUE TITLE
Crash when Install App

### ISSUE THREAD

**Issue by LenKiMo** [Iamlooker/Droid-ify#176]
Device: Xiaomi Mix 4
Android version: 12
ROM version: MIUI 13

Step:
- Open any app 
- Click download
- When download completed, click Install.
- Unable to install. The button backs to Download.
- Download again, and Click install notification from notification bar.
- Droid-ify crashes.

Error log provided by MIUI

```
java.io.FileNotFoundException: /data/user/0/com.looker.droidify/cache/releases/922087333a4fc62b13762379a29960a7521d8b5814634a8e8a7fca70061b51e4.apk: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:575)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at com.looker.droidify.installer.DefaultInstaller.mDefaultInstaller(DefaultInstaller.kt:52)
	at com.looker.droidify.installer.DefaultInstaller.install(DefaultInstaller.kt:36)
	at com.looker.droidify.screen.ScreenActivity$handleSpecialIntent$1.invokeSuspend(ScreenActivity.kt:224)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:256)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at com.looker.droidify.screen.ScreenActivity.handleSpecialIntent(ScreenActivity.kt:221)
	at com.looker.droidify.MainActivity.handleIntent(MainActivity.kt:19)
	at com.looker.droidify.screen.ScreenActivity.onNewIntent(ScreenActivity.kt:181)
	at android.app.Activity.performNewIntent(Activity.java:8262)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1429)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1442)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3963)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3970)
	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:56)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2272)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8210)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8085)
	at libcore.io.IoBridge.open(IoBridge.java:561)
	... 34 more
```

**Comment by machiav3lli** [comment]
MIUI optimizations on? If so turn them off

**Comment by machiav3lli** [comment]
MIUI optimizations on? If so turn them off

**Comment by LenKiMo** [comment]
Indeed it is the reason. thanks.
