### ISSUE TITLE
[Crash] Update repository

### ISSUE THREAD

**Issue by userkilled** [Iamlooker/Droid-ify#219]
**Describe the bug**

**To Reproduce**

**Smartphone (please complete the following information):**
 - Device: [e.g. Blackview BV6300Pro]
 - OS: [e.g. Android 10]
 - Version [e.g. v0.5.1]

**Additional context**
I add MyNero Repository :  
Address: https://mynero.net/fdroid/repo
Fingerprint: 0C 72 C5 40 E5 84 10 30 FA E3 23 29 A1 BC 87 47 DC AC 52 36 E4 D1 AA ED B6 77 35 CA 7B 7D D3 D6

**_LOG_**

FATAL EXCEPTION: DefaultDispatcher-worker-9
Process: com.looker.droidify, PID: 21045
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.SubList.rangeCheck(AbstractList.java:755)
	at java.util.SubList.get(AbstractList.java:639)
	at com.looker.droidify.index.RepositoryUpdater$update$3.invokeSuspend(RepositoryUpdater.kt:38)
	at com.looker.droidify.index.RepositoryUpdater$update$3.invoke(RepositoryUpdater.kt:13)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:5)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:72)
	at com.looker.droidify.index.RepositoryUpdater$update$3.invokeSuspend(RepositoryUpdater.kt:204)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:50)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:82)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@bd74bca, Dispatchers.IO]

**Comment by userkilled** [comment]
Site the project down. (Welcome to nginx)

**Comment by Iamlooker** [comment]
Well just a friendly reminder, If you cannot provide most of the info asked in the form you can select `Quick Bug Report` template

**Comment by Iamlooker** [comment]
This has been fixed. Well the fix is not that good, but its good enough for now as this issues was submitted very close to a release.

The current fix is:
 	If the website/repository is not accessible the `Add Repository` page will close after checking all the possible places. This is without any warning

Planned fix:
	Show a snackbar at bottom to notify the user that the repository was not added

**Comment by Iamlooker** [comment]
But as the repo is online I will close this issue for now

**Comment by Iamlooker** [comment]
Implemented the intended way :)
