### ISSUE TITLE
[Crash] Exit back from the application settings

### ISSUE THREAD

**Issue by userkilled** [Iamlooker/Droid-ify#234]
**Describe the bug**

 Exit back from the application settings

**Smartphone (please complete the following information):**
 - Device: Blackview bv6300 pro
 - OS: Android 10
 - Version  v0.5.3

**Additional context**

**LOGS**

FATAL EXCEPTION: main
Process: com.looker.droidify, PID: 5720
java.lang.UnsupportedOperationException
	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1106)
	at j$.util.Collection$-CC.$default$removeIf(SourceFile:0)
	at j$.util.Collection$-EL.removeIf(Unknown Source:11)
	at com.looker.feature_settings.SettingsViewModel.onCleared(SettingsViewModel.kt:10)
	at androidx.lifecycle.ViewModelStore.clear(ViewModelStore.java:92)
	at androidx.fragment.app.FragmentManagerViewModel.clearNonConfigStateInternal(FragmentManagerViewModel.java:27)
	at androidx.fragment.app.FragmentManagerViewModel.clearNonConfigState(FragmentManagerViewModel.java:29)
	at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:117)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java:6)
	at androidx.fragment.app.DefaultSpecialEffectsController$SpecialEffectsInfo.completeSpecialEffect(DefaultSpecialEffectsController.java:19)
	at androidx.fragment.app.DefaultSpecialEffectsController$2.onAnimationEnd(DefaultSpecialEffectsController.java:21)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1086)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:965)
	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
	at android.view.Choreographer.doFrame(Choreographer.java:722)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7386)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

**Comment by Iamlooker** [comment]
Closed with 2a59ba7b28a9cd9c71f04c3a83e8c9246197b950
