### ISSUE TITLE
App Crashing on Latest Version

### ISSUE THREAD

**Issue by g1t3m** [Iamlooker/Droid-ify#237]
Device: Google Pixel 6 Pro
OS: GrapheneOS, Android 13 (TQ1A.230105.002)
Droid-ify Version: 0.5.3

How to Replicate Issue:
1. Open Droid-ify
2. Sync repositories or go into Settings
3. If in Settings, exit Settings
4. If Syncing Repositories, wait a few seconds

Expected behavior: App stays open and repositories continue to sync.
Actual Behavior: App Crashes with following error:

```
type: crash
osVersion: google/raven/raven:13/TQ1A.230105.002/2023020200:user/release-keys
package: com.looker.droidify:53
process: com.looker.droidify
processUptime: 107025 + 219 ms

java.lang.UnsupportedOperationException
	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1128)
	at j$.util.Collection$-CC.$default$removeIf(SourceFile:0)
	at j$.util.Collection$-EL.removeIf(Unknown Source:11)
	at com.looker.feature_settings.SettingsViewModel.onCleared(SettingsViewModel.kt:22)
	at androidx.lifecycle.ViewModelStore.clear(ViewModelStore.java:92)
	at androidx.fragment.app.FragmentManagerViewModel.clearNonConfigStateInternal(FragmentManagerViewModel.java:27)
	at androidx.fragment.app.FragmentManagerViewModel.clearNonConfigState(FragmentManagerViewModel.java:29)
	at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:117)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java:6)
	at androidx.fragment.app.DefaultSpecialEffectsController$SpecialEffectsInfo.completeSpecialEffect(DefaultSpecialEffectsController.java:19)
	at androidx.fragment.app.DefaultSpecialEffectsController$2.onAnimationEnd(DefaultSpecialEffectsController.java:21)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:600)
	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1086)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:307)
	at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(Unknown Source:0)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:827)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7879)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

**Comment by Iamlooker** [comment]
Fixed in 0.5.4-0.5.5
