### ISSUE TITLE
Crash downloading / installing updates [0.3]

### ISSUE THREAD

**Issue by mahdi1234** [Iamlooker/Droid-ify#26]
With 0.3 (which I did not grant root permission, not sure whether related) it always crashes during app updates

LOS 17.1 / A10.

```
10-12 22:53:11.417 W/PropertyValuesHolder(27921): Method set() with type float not found on target class class com.looker.droidify.widget.FragmentLinearLayout
10-12 22:53:11.422 W/PropertyValuesHolder(27921): Method get() with type null not found on target class class com.looker.droidify.widget.FragmentLinearLayout
10-12 22:53:13.746 W/System.err(27921): java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Throwable.printStackTrace()' on a null object reference
10-12 22:53:13.746 W/System.err(27921): 	at com.looker.droidify.service.DownloadService.handleDownload$lambda-9(DownloadService.kt:448)
10-12 22:53:13.746 W/System.err(27921): 	at com.looker.droidify.service.DownloadService.$r8$lambda$PQqjbQoBmgHFfarV8D51DX3TTYg(Unknown Source:0)
10-12 22:53:13.746 W/System.err(27921): 	at com.looker.droidify.service.DownloadService$$ExternalSyntheticLambda0.accept(Unknown Source:10)
10-12 22:53:13.746 W/System.err(27921): 	at io.reactivex.rxjava3.internal.observers.BiConsumerSingleObserver.onSuccess(BiConsumerSingleObserver.java:56)
10-12 22:53:13.746 W/System.err(27921): 	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
10-12 22:53:13.746 W/System.err(27921): 	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
10-12 22:53:13.746 W/System.err(27921): 	at android.os.Handler.handleCallback(Handler.java:883)
10-12 22:53:13.746 W/System.err(27921): 	at android.os.Handler.dispatchMessage(Handler.java:100)
10-12 22:53:13.746 W/System.err(27921): 	at android.os.Looper.loop(Looper.java:214)
10-12 22:53:13.746 W/System.err(27921): 	at android.app.ActivityThread.main(ActivityThread.java:7357)
10-12 22:53:13.746 W/System.err(27921): 	at java.lang.reflect.Method.invoke(Native Method)
10-12 22:53:13.746 W/System.err(27921): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-12 22:53:13.746 W/System.err(27921): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
10-12 22:53:13.747 E/AndroidRuntime(27921): FATAL EXCEPTION: main
10-12 22:53:13.747 E/AndroidRuntime(27921): Process: com.looker.droidify, PID: 27921
10-12 22:53:13.747 E/AndroidRuntime(27921): java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Throwable.printStackTrace()' on a null object reference
10-12 22:53:13.747 E/AndroidRuntime(27921): 	at com.looker.droidify.service.DownloadService.handleDownload$lambda-9(DownloadService.kt:448)
10-12 22:53:13.747 E/AndroidRuntime(27921): 	at com.looker.droidify.service.DownloadService.$r8$lambda$PQqjbQoBmgHFfarV8D51DX3TTYg(Unknown Source:0)
10-12 22:53:13.747 E/AndroidRuntime(27921): 	at com.looker.droidify.service.DownloadService$$ExternalSyntheticLambda0.accept(Unknown Source:10)
10-12 22:53:13.747 E/AndroidRuntime(27921): 	at io.reactivex.rxjava3.internal.observers.BiConsumerSingleObserver.onSuccess(BiConsumerSingleObserver.java:56)
10-12 22:53:13.747 E/AndroidRuntime(27921): 	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
10-12 22:53:13.747 E/AndroidRuntime(27921): 	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
10-12 22:53:13.747 E/AndroidRuntime(27921): 	at android.os.Handler.handleCallback(Handler.java:883)
10-12 22:53:13.747 E/AndroidRuntime(27921): 	at android.os.Handler.dispatchMessage(Handler.java:100)
10-12 22:53:13.747 E/AndroidRuntime(27921): 	at android.os.Looper.loop(Looper.java:214)
10-12 22:53:13.747 E/AndroidRuntime(27921): 	at android.app.ActivityThread.main(ActivityThread.java:7357)
10-12 22:53:13.747 E/AndroidRuntime(27921): 	at java.lang.reflect.Method.invoke(Native Method)
10-12 22:53:13.747 E/AndroidRuntime(27921): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-12 22:53:13.747 E/AndroidRuntime(27921): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
10-12 22:53:13.774 I/Process (27921): Sending signal. PID: 27921 SIG: 9

```

**Comment by Iamlooker** [comment]
Can you try now with [this](https://github.com/Iamlooker/Droid-ify/releases/tag/v0.3.1)
