### ISSUE TITLE
Crash when installing app [RecyclerView Issue]

### ISSUE THREAD

**Issue by Wjxfi** [Iamlooker/Droid-ify#279]
the app closed by itself after installing https://www.f-droid.org/packages/com.yakovlevegor.DroidRec/. This has happened four times with different applications

These two logs were created at the same moment

>>FATAL EXCEPTION: DefaultDispatcher-worker-5
Process: com.looker.droidify, PID: 14915
java.lang.RuntimeException
	at com.looker.droidify.index.RepositoryUpdater$downloadIndex$2.invokeSuspend(RepositoryUpdater.kt:10)
	at com.looker.droidify.index.RepositoryUpdater$downloadIndex$2.invoke(RepositoryUpdater.kt:2)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
	at kotlinx.coroutines.DelayKt.withContext(Delay.kt:10)
	at com.looker.droidify.index.RepositoryUpdater$update$3.invokeSuspend(RepositoryUpdater.kt:7)
	at com.looker.droidify.index.RepositoryUpdater$update$3.invoke(RepositoryUpdater.kt:2)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
	at kotlinx.coroutines.DelayKt.withContext(Delay.kt:10)
	at com.looker.droidify.service.SyncService$handleFileDownload$job$1.invokeSuspend(SyncService.kt:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: >>[StandaloneCoroutine{Cancelling}@b710b7f, Dispatchers.IO]
>>

>FATAL EXCEPTION: main
Process: com.looker.droidify, PID: 28769
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 1(offset:-1).state:16 androidx.recyclerview.widget.RecyclerView{d7f3cb4 VFED..... ......ID 0,0-1080,2133 #102000a android:id/list}, adapter:com.looker.droidify.ui.app_detail.AppDetailAdapter@8777ab0, layout:androidx.recyclerview.widget.LinearLayoutManager@6610d29, context:dagger.hilt.android.internal.managers.ViewComponentManager$FragmentContextWrapper@742add9
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:965)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:59)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:54)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:858)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:367)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:64)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:8)
	at android.view.View.layout(View.java:23564)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23564)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:159)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:41)
	at android.view.View.layout(View.java:23564)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23564)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23564)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23564)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23564)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23564)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:865)
	at android.view.View.layout(View.java:23564)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3863)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3313)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2277)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9023)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1142)
	at android.view.Choreographer.doCallbacks(Choreographer.java:946)
	at android.view.Choreographer.doFrame(Choreographer.java:875)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1127)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
>

miui 13.0.5, android 12

**Comment by Iamlooker** [comment]
Can you please share a screen recording please?

**Comment by Iamlooker** [comment]
> session installer (not legacy and not shizuku, not root)

Can you try legacy installer, maybe that will fix the issue

**Comment by Iamlooker** [comment]
On MIUI you need to disable `MIUI Optimization` in developer options to make new mode working.

Check [here](https://youtu.be/Ag39ZBhb87E?t=14) on how to disable it.

**Comment by Iamlooker** [comment]
> Before the app update, I used the new mode and there were no bugs. The problem is with the app. I used the new loader all the time and everything was fine before updating your app.
> 
> that version - before you added the ability to copy text or earlier

When exactly did the isje started happening?

**Comment by Iamlooker** [comment]
Which was the previous version which you were using?

**Comment by Iamlooker** [comment]
> I just had the application close by itself in legacy mode
> 
> This problem has not been solved. Reopen the issue.

Can you share crash log

**Comment by Iamlooker** [comment]
does the crash occur after the app is installed or when you click on install button?

**Comment by Iamlooker** [comment]
@Wjxfi and @shuvashish76 please check if this fixes the issues. Build files will be available in GitHub Actions soon

**Comment by shuvashish76** [comment]
Installed & tried installations few apps, no such crashes yet.
I'll report here if it crashes in future as it's a occasional crash & I'm not sure how to reproduce it.
I think for now you can close this issue, thanks.
