### ISSUE TITLE
[Crash] while scrolling favorites

### ISSUE THREAD

**Issue by uli-on** [Iamlooker/Droid-ify#336]
**Describe the bug**
Droid-ify crashes consistently when scrolling down my favorites list.

**To Reproduce**
1. Open the favorites screen, that should contain a sufficient amount of entries to cause it to scroll. In my case it's 13.
2. Begin scrolling, quickly or pixel by pixel, regardless:
3. Droid-ify crashes at a certain point, that is probably the last item

**Smartphone:**
 - Device: Fairphone 3
 - OS: Android 10, not rooted, no nothing
  - Play Services v23.13.12
  - System webview v111.0.5563.116
 - Droidify Version 0.5.7

**Additional context**
```
FATAL EXCEPTION: main
Process: com.looker.droidify, PID: 21266
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:8)
	at com.looker.droidify.ui.favourites.FavouriteFragmentAdapter.onBindViewHolder(FavouriteFragmentAdapter.kt:11)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:1)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:1165)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:46)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:172)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:74)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Comment by Iamlooker** [comment]
This was fixed and will be available in next update

**Comment by uli-on** [comment]
Thanks very much :)
